apiVersion: v1
kind: Service
metadata:
  name: rpcv2-hist
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8899
  selector:
    app: rpcv2-hist
    
