name: bench

on:
  schedule:
    - cron: '0 2 * * *'   # nightly 02:00 UTC
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build -o bench ./cmd/bench
      - run: echo "Bench skipped in CI (no 2.3 B rows)"
      
